### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by plutonium-239** [nairouz/FT-VGAE#1]
Hi, I'm unable to run this, as there are no pretrained weights that the model needs and they are not available at the mentioned https://github.com/zfjsail/gae-pytorch/ repo either, and their training code does not save a model either.

Could you please provide either the training weights directly (preferable) or a code that trains the model and saves weights usable by this code?

I did try running their code and saving a model, but it expects different layers:
```
RuntimeError: Error(s) in loading state_dict for FT_VGAE:
        Missing key(s) in state_dict: "base_gcn.weight", "gcn_mean.weight", "gcn_logsigma2.weight", "assignment_1.cluster_centers".
        Unexpected key(s) in state_dict: "gc1.weight", "gc2.weight", "gc3.weight".
```
So is that repo not being used anymore?

**Comment by nairouz** [comment]
Thank you for your interest.
I have provided the pretraining weights for two datasets: Cora and Citeseer. Please check the code now.
You should be able to reproduce the same results as the paper. 
Let me know if there is a problem

**Comment by GPhMorin** [comment]
Hello,  
In the past four days, the only changes that have been applied is a new `model_best.pk` for Citeseer. Is that where the weights should be found?

![IMG_1907](https://user-images.githubusercontent.com/6393838/235159432-e271b3c4-e5f6-456e-af77-7741a85c1a56.png)

**Comment by nairouz** [comment]
I have added the pretraining weights for Cora and Citeseer.
Yes, you can find the pretraining weights in the folder (FT-VGAE/tree/main/results/Cora and FT-VGAE/tree/main/results/Citeseer).
